name: CI_AutoMerge_Dependabot

on:
  pull_request:
    paths-ignore: # https://docs.github.com/en/actions/reference/workflow-syntax-for-github-actions#filter-pattern-cheat-sheet
      - '**/README.md'
      - '**/dependabot.yml'
      - 'docs/*'
      - '.vscode/*'
    branches:
      - develop
      - main

jobs:
  build-test-node:
    runs-on: ubuntu-latest
    steps:
      - name: 'Install libxml2-utils'
        run: |
          sudo apt-get update && \
          sudo apt-get install libxml2-utils

      - name: 'Checkout GitHub Action'
        uses: actions/checkout@v3

      - name: 'Setup Node Environment'
        uses: actions/setup-node@v3.4.1
        with:
          node-version-file: '.nvmrc'
          cache: 'npm'

      - name: 'Install Dependencies with Npm'
        run: |
          npm i -g npm
          npm ci

      - name: 'Run unit tests'
        run: npm run rules:test

  build-docker:
    runs-on: ubuntu-latest
    steps:
      - name: 'Checkout GitHub Action'
        uses: actions/checkout@v3

      - name: 'Build Docker Image'
        run: |
          docker build . -t validator-local:latest

  automerge:
    needs: [build-test-node, build-docker]
    runs-on: ubuntu-latest
    permissions:
      pull-requests: write
      contents: write
    steps:
      - uses: fastify/github-action-merge-dependabot@v3.3.0
        with:
          github-token: ${{secrets.GITHUB_TOKEN}}
