name: CI_AutoMerge_Dependabot

on:
  pull_request:
    paths-ignore: # https://docs.github.com/en/actions/reference/workflow-syntax-for-github-actions#filter-pattern-cheat-sheet
      - '**/README.md'
      - '**/dependabot.yml'
    branches:
      - develop
      - main

env:
  NODE_VERSION: '14.x'

jobs:
  build-test:
    runs-on: ubuntu-latest
    steps:
      - name: 'Install libxml2-utils'
        run: |
          sudo apt-get update && \
          sudo apt-get install libxml2-utils

      - name: 'Checkout GitHub Action'
        uses: actions/checkout@v2.3.4

      - name: 'Setup Node ${{ env.NODE_VERSION }} Environment'
        uses: actions/setup-node@v2.4.0
        with:
          node-version: ${{ env.NODE_VERSION }}

      - name: Cache node modules
        uses: actions/cache@v2.1.6
        env:
          cache-name: cache-node-modules
        with:
          # npm cache files are stored in `~/.npm` on Linux/macOS
          path: ~/.npm
          key: ${{ runner.os }}-build-${{ env.cache-name }}-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-build-${{ env.cache-name }}-
            ${{ runner.os }}-build-
            ${{ runner.os }}-

      - name: 'Install Dependencies with Npm'
        run: npm install

      - name: 'Run unit tests'
        run: npm run rules:test

  automerge:
    needs: build-test
    runs-on: ubuntu-latest
    steps:
      - uses: fastify/github-action-merge-dependabot@v2.4.0
        with:
          github-token: ${{secrets.GITHUB_TOKEN}}
