name: CI_AutoMerge_Dependabot

on:
  pull_request:
    paths-ignore: # https://docs.github.com/en/actions/reference/workflow-syntax-for-github-actions#filter-pattern-cheat-sheet
      - '**/README.md'
      - '**/dependabot.yml'
      - 'docs/*'
    branches:
      - develop
      - main

env:
  NODE_VERSION: '14.x'

jobs:
  build-test-node:
    runs-on: ubuntu-latest
    steps:
      - name: 'Install libxml2-utils'
        run: |
          sudo apt-get update && \
          sudo apt-get install libxml2-utils

      - name: 'Checkout GitHub Action'
        uses: actions/checkout@v2.4.0

      - name: 'Setup Node ${{ env.NODE_VERSION }} Environment'
        uses: actions/setup-node@v2.5.0
        with:
          node-version: ${{ env.NODE_VERSION }}
          cache: 'npm'

      - name: 'Install Dependencies with Npm'
        run: |
          npm i -g npm
          npm install

      - name: 'Run unit tests'
        run: npm run rules:test

  build-docker:
    runs-on: ubuntu-latest
    steps:
      - name: 'Checkout GitHub Action'
        uses: actions/checkout@v2.4.0

      - name: 'Build Docker Image'
        run: |
          docker build . -t validator-local:latest

  automerge:
    needs: [build-test-node, build-docker]
    runs-on: ubuntu-latest
    steps:
      - uses: fastify/github-action-merge-dependabot@v3.0.2
        with:
          github-token: ${{secrets.GITHUB_TOKEN}}
